import { EmbroideryOrderItem } from "@/src/features/embroidery-quotes/interfaces/embroidery-quote.interface";
import { ProductionOrderItem } from "@/src/features/production-quotes/interfaces/production-quote.interface";
import { PurchaseOrderItem } from "@/src/features/purchase-quotes/interfaces/purchase-quote.interface";

export const EMBROIDERY_ORDERS_DATA: EmbroideryOrderItem[] = [
  {
    id: "EMB-001",
    pedido: "PED-3101",
    cliente: "Textiles Andina",
    fecha: "18 Feb 2026",
    estatus: "En proceso",
    piezas: 120,
    total: 18500,
  },
  {
    id: "EMB-002",
    pedido: "PED-3102",
    cliente: "Uniformes Atlas",
    fecha: "19 Feb 2026",
    estatus: "Acción requerida",
    piezas: 80,
    total: 9200,
  },
  {
    id: "EMB-003",
    pedido: "PED-3095",
    cliente: "Grupo Boreal",
    fecha: "16 Feb 2026",
    estatus: "En proceso",
    piezas: 55,
    total: 6100,
  },
  {
    id: "EMB-004",
    pedido: "PED-3090",
    cliente: "Corporativo Solaris",
    fecha: "14 Feb 2026",
    estatus: "Demorado",
    piezas: 200,
    total: 32400,
  },
  {
    id: "EMB-005",
    pedido: "PED-3105",
    cliente: "Industrias Prisma",
    fecha: "20 Feb 2026",
    estatus: "Completado",
    piezas: 150,
    total: 24800,
  },
];

export const PRODUCTION_ORDERS_DATA: ProductionOrderItem[] = [
  {
    id: "PROD-001",
    pedido: "PED-3201",
    cliente: "Moda Integral",
    fecha: "17 Feb 2026",
    estatus: "En proceso",
    piezas: 320,
    total: 58200,
  },
  {
    id: "PROD-002",
    pedido: "PED-3202",
    cliente: "Industria Nimbus",
    fecha: "18 Feb 2026",
    estatus: "Demorado",
    piezas: 150,
    total: 27650,
  },
  {
    id: "PROD-003",
    pedido: "PED-3198",
    cliente: "Distribuidora Lumen",
    fecha: "15 Feb 2026",
    estatus: "Acción requerida",
    piezas: 210,
    total: 38900,
  },
  {
    id: "PROD-004",
    pedido: "PED-3190",
    cliente: "Corporativo Zenith",
    fecha: "13 Feb 2026",
    estatus: "Completado",
    piezas: 400,
    total: 74500,
  },
  {
    id: "PROD-005",
    pedido: "PED-3207",
    cliente: "Telas del Norte",
    fecha: "20 Feb 2026",
    estatus: "Pendiente",
    piezas: 95,
    total: 18400,
  },
];

export const PURCHASE_ORDERS_DATA: PurchaseOrderItem[] = [
  {
    id: "COMP-001",
    pedido: "OC-5601",
    proveedor: "Textiles del Sur",
    fecha: "18 Feb 2026",
    estatus: "En proceso",
    piezas: 500,
    total: 96400,
  },
  {
    id: "COMP-002",
    pedido: "OC-5602",
    proveedor: "Suministros Orion",
    fecha: "19 Feb 2026",
    estatus: "Acción requerida",
    piezas: 220,
    total: 38850,
  },
  {
    id: "COMP-003",
    pedido: "OC-5595",
    proveedor: "Empaques Nova",
    fecha: "16 Feb 2026",
    estatus: "Demorado",
    piezas: 140,
    total: 15200,
  },
  {
    id: "COMP-004",
    pedido: "OC-5580",
    proveedor: "Hilaturas Sierra",
    fecha: "12 Feb 2026",
    estatus: "Completado",
    piezas: 300,
    total: 52500,
  },
  {
    id: "COMP-005",
    pedido: "OC-5610",
    proveedor: "Tinturas Prisma",
    fecha: "20 Feb 2026",
    estatus: "Pendiente",
    piezas: 90,
    total: 11800,
  },
];
