import {
  DashboardIcon,
  ClientesIcon,
  InventariosIcon,
  ComprasIcon,
  SettingsIcon,
  ListaPreciosIcon,
  CapitalHumanoIcon,
  OperationsIcon,
} from "../components/Icons";

const defaultCardClassName =
  "cursor-pointer rounded-2xl bg-white dark:bg-black border border-slate-200 dark:border-white/10 p-8 h-full";

export const homeCards = [
  {
    icon: DashboardIcon,
    title: "Panel de Control (Core)",
    description: "Empresas, usuarios, seguridad y catálogos base del sistema.",
    footerText: "Configurar estructura",
    href: "/system",
    accentClass: "text-sky-600 dark:text-sky-400",
    accentBgClass: "bg-sky-50 dark:bg-sky-500/10",
    shadowColorClassName: "hover:shadow-sky-500/25 dark:hover:shadow-sky-500/25",
    permission: "R-CORE",
    className: defaultCardClassName,
  },
  {
    icon: ClientesIcon,
    title: "CRM y Ventas",
    description: "Prospectos, oportunidades, actividades, cotizaciones y pedidos centralizados.",
    footerText: "Ver flujo comercial",
    href: "/sales",
    accentClass: "text-rose-600 dark:text-rose-400",
    accentBgClass: "bg-rose-50 dark:bg-rose-500/10",
    shadowColorClassName: "hover:shadow-rose-500/25 dark:hover:shadow-rose-500/25",
    permission: "R-CRM",
    className: defaultCardClassName,
  },
  {
    icon: InventariosIcon,
    title: "Operaciones de Almacén (WMS)",
    description: "Inventario, ubicaciones, movimientos, picking, packing y transferencias.",
    footerText: "Gestionar almacenes",
    href: "/wms",
    accentClass: "text-emerald-600 dark:text-emerald-400",
    accentBgClass: "bg-emerald-50 dark:bg-emerald-500/10",
    shadowColorClassName: "hover:shadow-emerald-500/25 dark:hover:shadow-emerald-500/25",
    permission: "R-WMS",
    className: `${defaultCardClassName} transition-all duration-300`,
  },
  {
    icon: ComprasIcon,
    title: "Compras y SCM",
    description: "Requisiciones, cotizaciones proveedor, órdenes de compra y recepciones.",
    footerText: "Control de abastecimiento",
    href: "/procurement",
    accentClass: "text-amber-600 dark:text-amber-400",
    accentBgClass: "bg-amber-50 dark:bg-amber-500/10",
    shadowColorClassName: "hover:shadow-amber-500/25 dark:hover:shadow-amber-500/25",
    permission: "R-COMPRAS",
    className: defaultCardClassName,
  },
  {
    icon: SettingsIcon,
    title: "Manufactura (Producción)",
    description: "BOM, rutas, órdenes de producción, avances y consumos de material.",
    footerText: "Ver planta productiva",
    href: "/manufacturing",
    accentClass: "text-indigo-600 dark:text-indigo-400",
    accentBgClass: "bg-indigo-50 dark:bg-indigo-500/10",
    shadowColorClassName: "hover:shadow-indigo-500/25 dark:hover:shadow-indigo-500/25",
    permission: "R-PRODUCCION",
    className: defaultCardClassName,
  },
  {
    icon: ListaPreciosIcon,
    title: "Finanzas y Contabilidad",
    description: "Facturación, CxC, CxP, tesorería, bancos y contabilidad general.",
    footerText: "Revisar finanzas",
    href: "/finance",
    accentClass: "text-emerald-600 dark:text-emerald-400",
    accentBgClass: "bg-emerald-50 dark:bg-emerald-500/10",
    shadowColorClassName: "hover:shadow-emerald-500/25 dark:hover:shadow-emerald-500/25",
    permission: "R-CONTABILIDAD",
    className: defaultCardClassName,
  },
  {
    icon: CapitalHumanoIcon,
    title: "Capital Humano (HR)",
    description: "Plantilla, asistencia, nómina y desempeño del talento de la organización.",
    footerText: "Ver equipo",
    href: "/hr",
    accentClass: "text-teal-600 dark:text-teal-400",
    accentBgClass: "bg-teal-50 dark:bg-teal-500/10",
    shadowColorClassName: "hover:shadow-teal-500/25 dark:hover:shadow-teal-500/25",
    permission: "R-RH",
    className: defaultCardClassName,
  },
  // {
  //   icon: DashboardIcon,
  //   title: "Otros Módulos",
  //   description: "Proyectos, e-commerce, canales digitales, marketing y campañas segmentadas.",
  //   footerText: "Explorar módulos",
  //   href: "/other",
  //   accentClass: "text-fuchsia-600 dark:text-fuchsia-400",
  //   accentBgClass: "bg-fuchsia-50 dark:bg-fuchsia-500/10",
  //   shadowColorClassName: "hover:shadow-fuchsia-500/25 dark:hover:shadow-fuchsia-500/25",
  //   permission: "R-OTROS-MODULOS",
  //   className: defaultCardClassName,
  // },
  {
    icon: OperationsIcon,
    title: "Mesa de Control",
    description: "Panel de control general de la organización, con visión global de las operaciones y rendimiento.",
    footerText: "Ver control general",
    href: "/operations",
    accentClass: "text-fuchsia-600 dark:text-fuchsia-400",
    accentBgClass: "bg-fuchsia-50 dark:bg-fuchsia-500/10",
    shadowColorClassName: "hover:shadow-fuchsia-500/25 dark:hover:shadow-fuchsia-500/25",
    permission: "R-MESACONTROL",
    className: defaultCardClassName,
  }
] as const;
