export const routePermissions = [
  { prefix: "/config", permission: "R-CONF" },
  { prefix: "/orders", permission: "R-PEDID" },
  { prefix: "/production", permission: "R-PROD" },
  { prefix: "/inventories", permission: "R-INVE" },
  { prefix: "/orders-menu", permission: "R-ORDE" },
  { prefix: "/receipts", permission: "R-RECE" },
  { prefix: "/invoicing", permission: "R-FACT" },
  { prefix: "/accounts-payable", permission: "R-CUXP" },
  { prefix: "/accounts-receivable", permission: "R-CUXC" },
  { prefix: "/bank-accounts", permission: "R-BANC" },
  { prefix: "/accounting", permission: "R-CONT" },
  { prefix: "/stock", permission: "R-EXIS" },
  { prefix: "/price-lists", permission: "R-PREC" },
  { prefix: "/shipment-tracking", permission: "R-GUIA" },
  { prefix: "/customers", permission: "R-CLIE" },
  { prefix: "/shipments", permission: "R-EMBA" },
  { prefix: "/reports", permission: "R-REPO" },
];