export const routePermissions = [
  { prefix: "/config", permission: "R-CONF" },
  { prefix: "/system/reports", permission: "R-REPO" },
  { prefix: "/sales/customers", permission: "R-CLIE" },
  { prefix: "/sales/orders", permission: "R-PEDID" },
  { prefix: "/wms/inventories", permission: "R-INVE" },
  { prefix: "/wms/stock", permission: "R-EXIS" },
  { prefix: "/wms/shipments", permission: "R-EMBA" },
  { prefix: "/wms/shipment-tracking", permission: "R-GUIA" },
  { prefix: "/procurement/orders-menu", permission: "R-ORDE" },
  { prefix: "/procurement/receipts", permission: "R-RECE" },
  { prefix: "/manufacturing/production", permission: "R-PROD" },
  { prefix: "/finance/invoicing", permission: "R-FACT" },
  { prefix: "/finance/accounts-payable", permission: "R-CUXP" },
  { prefix: "/finance/accounts-receivable", permission: "R-CUXC" },
  { prefix: "/finance/bank-accounts", permission: "R-BANC" },
  { prefix: "/finance/accounting", permission: "R-CONT" },
  { prefix: "/finance/price-lists", permission: "R-PREC" },
];
