export interface LoginResponse {
    token:            string;
    user_id:          number;
    email:            string;
    username:         string;
    nombre_completo:  string;
    es_admin:         boolean;
    is_superuser:     boolean;
    is_admin_empresa: boolean;
    empresa_id:       number;
    permisos:         Permission[];
}

type Permission =
  | "D-BANC"
  | "D-CLIE"
  | "D-CONF"
  | "D-CONT"
  | "D-CUXC"
  | "D-CUXP"
  | "D-EMBA"
  | "D-EXIS"
  | "D-FACT"
  | "D-GUIA"
  | "D-INVE"
  | "D-ORDE"
  | "D-PEDID"
  | "D-PREC"
  | "D-PROD"
  | "D-RECE"
  | "D-REPO"
  | "E-BANC"
  | "E-CLIE"
  | "E-CONF"
  | "E-CONT"
  | "E-CUXC"
  | "E-CUXP"
  | "E-EMBA"
  | "E-EXIS"
  | "E-FACT"
  | "E-GUIA"
  | "E-INVE"
  | "E-ORDE"
  | "E-PEDID"
  | "E-PREC"
  | "E-PROD"
  | "E-RECE"
  | "E-REPO"
  | "R-BANC"
  | "R-CLIE"
  | "R-CONF"
  | "R-CONT"
  | "R-CUXC"
  | "R-CUXP"
  | "R-EMBA"
  | "R-EXIS"
  | "R-FACT"
  | "R-GUIA"
  | "R-INVE"
  | "R-ORDE"
  | "R-PEDID"
  | "R-PREC"
  | "R-PROD"
  | "R-RECE"
  | "R-REPO"
