import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/auth";
import "./globals.css";
import { Provider } from "./Provider";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} antialiased`}
      >
        <Provider session={session}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
