import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/auth";
import "@radix-ui/themes/styles.css";
import "react-color-palette/css";
import "./globals.css";
import "./styles/fullcalendar.css";
import { Provider } from "./Provider";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    /*
     * suppressHydrationWarning es necesario porque el script de inicialización
     * de tema puede añadir la clase 'dark' al elemento <html> antes de que React
     * hidrate, lo que causaría un mismatch detectado por el hydration checker.
     */
    <html lang="en" suppressHydrationWarning>
      <head>
        {/*
         * Script anti-FOUC (Flash Of Unstyled Content) de tema.
         * Se ejecuta de forma síncrona ANTES de que el navegador pinte el primer
         * frame, aplicando la clase 'dark' en <html> según la preferencia guardada
         * en localStorage o la preferencia del sistema operativo.
         * Estrategia: light → sin clase | dark → clase 'dark' | system/null → matchMedia
         */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');if(t==='dark'){document.documentElement.classList.add('dark')}else if(t==='light'){document.documentElement.classList.remove('dark')}else{if(window.matchMedia('(prefers-color-scheme:dark)').matches){document.documentElement.classList.add('dark')}}}catch(e){}})();`,
          }}
        />
      </head>
      <body
        className={`${inter.variable} ${poppins.variable} antialiased`}
      >
        <Provider session={session}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
