import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Provider } from "./Provider";



// Inter es la fuente del cuerpo (texto base): se precarga porque se usa
// inmediatamente above-the-fold en todas las rutas.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

// Poppins es la fuente secundaria (solo títulos/brand-font). Se desactiva el
// preload para no competir con la descarga del recurso LCP: el navegador la
// carga al usarse y, gracias al fallback ajustado por métricas (size-adjust),
// el texto se pinta de inmediato sin FOIT ni desplazamiento de layout (CLS).
// Evita precargar 5 pesos de fuente que en muchas rutas no se usan above-the-fold.
const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    /*
     * suppressHydrationWarning es necesario porque el script de inicialización
     * de tema puede añadir la clase 'dark' al elemento <html> antes de que React
     * hidrate, lo que causaría un mismatch detectado por el hydration checker.
     */
    <html lang="en" suppressHydrationWarning>
      <head>
        {/*
         * Script anti-FOUC (Flash Of Unstyled Content) de tema.
         * Se ejecuta de forma síncrona ANTES de que el navegador pinte el primer
         * frame, aplicando la clase 'dark' en <html> según la preferencia guardada
         * en localStorage o la preferencia del sistema operativo.
         * Estrategia: light → sin clase | dark → clase 'dark' | system/null → matchMedia
         *
         * Además, parchea performance.measure para silenciar el error dev-only
         * "negative time stamp" de la instrumentación RSC de Next.js (issue #86060),
         * presente en ambos bundlers. Re-lanza cualquier otro error real sin tocarlo.
         * El guard __patched evita doble parcheo entre recargas de Fast Refresh.
         */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var s=localStorage.getItem('theme-storage');var t=s?JSON.parse(s)?.state?.theme:null;if(t==='dark'){document.documentElement.classList.add('dark')}else if(t==='light'){document.documentElement.classList.remove('dark')}else{if(window.matchMedia('(prefers-color-scheme:dark)').matches){document.documentElement.classList.add('dark')}}}catch(e){}})();(function(){try{var perf=window.performance;if(!perf||typeof perf.measure!=="function"||perf.__patched)return;var original=perf.measure.bind(perf);perf.measure=function(){try{return original.apply(perf,arguments)}catch(err){var msg=(err&&err.message)||"";var name=(err&&err.name)||"";if(msg.indexOf("negative time stamp")!==-1||name==="InvalidAccessError"||name==="SyntaxError"){return}throw err}};perf.__patched=true}catch(_){}})();`,
          }}
        />
      </head>
      <body
        className={`${inter.variable} ${poppins.variable} antialiased`}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
