import { QuoteExtraService } from "../../quotes/interfaces/quote.interface";

export interface Order {
  id: number;
  folio: string;
  folio_consecutivo: number;
  servicios_extras: QuoteExtraService[];
  tipo_pedido: number;
  estatus: number;
  persona_pagos: string;
  correo_facturas: string;
  telefono_pagos: string;
  oc: string;
  forma_pago: string;
  metodo_pago: string;
  uso_cfdi: string;
  cliente_razon_social: string;
  cliente_nombre: string;
  cliente_rfc: string;
  cliente_direccion_fiscal: string;
  cliente_colonia: string;
  cliente_codigo_postal: string;
  cliente_ciudad: string;
  cliente_estado: string;
  anticipo_total: boolean;
  anticipo_parcial: boolean;
  vendedor_autoriza: boolean;
  pago_antes_embarque: boolean;
  por_confirmar: boolean;
  otra_cantidad: boolean;
  monto: string;
  embarque_parcial: boolean;
  comentarios_parcialidad: string;
  destinatario: string | null;
  empresa_envio: string | null;
  telefono_envio: string | null;
  celular_envio: string | null;
  direccion_envio: string | null;
  colonia_envio: string | null;
  codigo_postal: string | null;
  ciudad_envio: string | null;
  estado_envio: string | null;
  referencias: string | null;
  envio: string;
  programa_bordados: string;
  bordado_pantalones_extras: string;
  bordado_logotipo: boolean;
  serigrafia: string;
  reflejante: string;
  observaciones: string;
  flete: string;
  seguros: string;
  anticipo: string;
  subtotal: string;
  descuento_global: string;
  ieps: string;
  iva: number;
  gran_total: string;
  activo: boolean;
  created_at: string;
  updated_at: string;
  fecha_confirmacion: string | null;
  empresa: number;
  sucursal: number;
  serie_folio: number;
  cliente: number;
  cotizacion: number | null;
  moneda: number;
  cliente_regimen_fiscal: number;
}